const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..', '点餐小程序的用户端');
const source = fs.readFileSync(path.join(root, 'common/glass-motion.js'), 'utf8');
let callback, now = 1000, writes = 0;
const query = { in() { return this; }, select() { return this; }, boundingClientRect(cb) { callback = cb; return this; }, exec() {} };
const context = { uni: { createSelectorQuery: () => query }, Date: { now: () => now }, Number, Math };
vm.runInNewContext(source.replace(/export function /g, 'function ').replace('export default', 'var mixin ='), context);
const mixin = context.mixin;
const state = { ...mixin.data(), $set(target, key, value) { target[key] = value; writes++; } };
for (const [name, method] of Object.entries(mixin.methods)) state[name] = method.bind(state);
const event = (x, y) => ({ touches: [{ clientX: x, clientY: y }] });
const rect = { left: 10, top: 20, width: 100, height: 50 };
assert.equal(context.glassPoint({ touches: [] }), null);
assert.equal(context.glassPoint({ touches: [{ clientX: NaN, clientY: 0 }] }), null);
assert.equal(context.mapGlassPoint({ x: -20, y: 200 }, rect).x, 0);
assert.equal(context.mapGlassPoint({ x: -20, y: 200 }, rect).y, 100);
state.glassStart('dine', event(35, 30));
callback(rect);
assert.equal(state.glassTouches.dine.x, 25);
assert.equal(state.glassTouches.dine.y, 20);
assert.equal(state.glassPressed('dine'), true);
state.glassMove('dine', event(60, 32));
assert.equal(state.glassTouches.dine.x, 50);
const previousWrites = writes;
now += 5;
state.glassMove('dine', event(70, 33));
assert.equal(writes, previousWrites, 'touchmove updates are throttled');
state.glassEnd('dine');
assert.equal(state.glassPressed('dine'), false);
state.glassStart('dine', event(35, 30));
const staleCallback = callback;
state.glassEnd('dine');
staleCallback(rect);
assert.equal(state.glassPressed('dine'), false, 'late query cannot re-press a released card');
state.glassStart('dine', event(35, 30));
callback(rect);
now += 100;
state.glassMove('dine', event(36, 80));
assert.equal(state.glassPressed('dine'), false, 'vertical scrolling releases decoration');
state.glassStart('dock', event(35, 30));
state.glassMove('dock', { touches: [{ clientX: 35, clientY: 30 }, { clientX: 45, clientY: 30 }] });
assert.equal(state.glassPressed('dock'), false, 'multi-touch cancels decoration');
state.glassStart('dock', event(35, 30));
const hideCallback = callback;
mixin.onHide.call(state);
hideCallback(rect);
assert.equal(state.glassPressed('dock'), false, 'page hide invalidates pending measurements');
assert.equal(state.glassStyle('missing')['--glass-x'], '50%');
context.uni.createSelectorQuery = () => { throw new Error('unsupported'); };
assert.doesNotThrow(() => state.glassStart('user', event(10, 20)));
assert.equal(state.glassPressed('user'), true, 'centered fallback works without geometry');
mixin.beforeDestroy.call(state);
assert.equal(Object.keys(state.glassTouches).length, 0);
const css = fs.readFileSync(path.join(root, 'common/scss/glass-motion.scss'), 'utf8');
assert.ok(css.includes('prefers-reduced-motion'));
assert.ok(css.includes('pointer-events: none'));
assert.ok(!source.includes('preventDefault') && !source.includes('switchTab') && !source.includes('setInterval'));
console.log('PASS: touch mapping, bounds, throttling, release, cancel, scroll, stale callbacks, hide/destroy cleanup and reduced-motion fallback');
